/** Original Blender animation clips. Generated by scripts/3d/pack.mjs. */
export const CAT_SPRITE_CATALOG = {
  idle: { frameCount: 24, fps: 12 },
  idle2: { frameCount: 24, fps: 12 },
  sleep: { frameCount: 24, fps: 12 },
  dance: { frameCount: 20, fps: 16 },
  sleepy: { frameCount: 24, fps: 16 },
  excited: { frameCount: 20, fps: 16 },
  layDown: { frameCount: 24, fps: 12 },
  sad: { frameCount: 24, fps: 12 },
  cry: { frameCount: 20, fps: 12 },
  box2: { frameCount: 24, fps: 16 },
  box1: { frameCount: 16, fps: 16 },
  box3: { frameCount: 16, fps: 16 },
  surprised: { frameCount: 20, fps: 16 },
  eating: { frameCount: 32, fps: 16 },
  waiting: { frameCount: 20, fps: 16 },
  blinkIdle: { frameCount: 24, fps: 12 },
  angryCute: { frameCount: 20, fps: 12 },
  blinkSit: { frameCount: 24, fps: 12 },
  correct: { frameCount: 24, fps: 20 },
  incorrect: { frameCount: 24, fps: 16 },
  lieDown: { frameCount: 24, fps: 16 },
  restSleep: { frameCount: 24, fps: 16 },
} as const;
export type CatSpriteAnimationId = keyof typeof CAT_SPRITE_CATALOG;
export type CatSpriteCatalogEntry = (typeof CAT_SPRITE_CATALOG)[CatSpriteAnimationId];
