/** Auto-generated frame lists for TV animations. */

export const BIG_TV_A_ANIM_FRAMES = [
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-01.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-02.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-03.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-04.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-05.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-06.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-07.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-08.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-09.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-10.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-11.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-12.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-13.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-14.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-15.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-16.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-17.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-18.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvA/frame-19.png"),
] as const;

export const BIG_TV_B_ANIM_FRAMES = [
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-01.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-02.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-03.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-04.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-05.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-06.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-07.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-08.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-09.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-10.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-11.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-12.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-13.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-14.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-15.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-16.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-17.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-18.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-19.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/BigTvB/frame-20.png"),
] as const;

export const TV_DVD_ANIM_FRAMES = [
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-01.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-02.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-03.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-04.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-05.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-06.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-07.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-08.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-09.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-10.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-11.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-12.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-13.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-14.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-15.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-16.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-17.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-18.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-19.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-20.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-21.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-22.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-23.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-24.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-25.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-26.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-27.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-28.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-29.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-30.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-31.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-32.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-33.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-34.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-35.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-36.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-37.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-38.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-39.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-40.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-41.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-42.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-43.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-44.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-45.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-46.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-47.png"),
  require("@/assets/pets/Cat/CatItems/Decorations/TVs/TvDvd/frame-48.png"),
] as const;
