"""Export the game's original models and all cat actions for native Filament.
Blender --background --python scripts/3d/export-native.py -- [--items|--cats]
The saved catalog IDs and the original raster framing are retained in metadata.
"""
from pathlib import Path
import bpy, sys, math, json
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT/'scripts/3d'))
from native_gltf import normalize_animation_times
OUT=ROOT/'assets/3d/native';OUT.mkdir(parents=True,exist_ok=True)
scope={'__file__':str(ROOT/'scripts/3d/render_assets.py'),'__name__':'__native_assets__'}
exec(compile((ROOT/'scripts/3d/render_assets.py').read_text(),scope['__file__'],'exec'),scope)
ARGS=sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else []
def clear():
 bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
def export(path,objects,animated=False):
 bpy.ops.object.select_all(action='DESELECT')
 for o in objects:o.select_set(True)
 bpy.context.view_layer.objects.active=objects[0]
 bpy.context.view_layer.update()
 temporary=path.with_name(path.stem+'-export.glb')
 bpy.ops.export_scene.gltf(filepath=str(temporary),export_format='GLB',use_selection=True,export_yup=True,export_extras=True,export_apply=not path.name.startswith('cat-'),export_animations=animated,export_animation_mode='NLA_TRACKS',export_force_sampling=True,export_frame_range=True,export_anim_slide_to_zero=True)
 normalize_animation_times(temporary)
 temporary.replace(path)
def bounds(objects):
 bpy.context.view_layer.update()
 points=[o.matrix_world@Vector(c) for o in objects if o.type in ('MESH','CURVE') for c in o.bound_box]
 return [min(v[i] for v in points) for i in range(3)],[max(v[i] for v in points) for i in range(3)]
def items():
 metadata={}
 for entry in json.loads((ROOT/'scripts/3d/inventory.json').read_text())['entries']:
  clear();scene=scope['setup'](256);id=entry['id'];kind=entry['kind']
  if kind=='room':
   # Reuse the original room builder without producing another raster or .blend.
   previous=scope['render'];scope['render']=lambda path:None
   save=bpy.ops.wm.save_as_mainfile
   # Extract only the model-building part; room() also saves an external library.
   code=(ROOT/'scripts/3d/render_assets.py').read_text();start=code.index('def room(entry):');end=code.index(" render(OUT/'rooms'",start)
   exec(code[start:end].replace('def room(entry):','def native_room(entry):'),scope);scope['native_room'](entry)
   scope['render']=previous
   objects=[o for o in bpy.context.scene.objects if o.type=='MESH'];render_scale=7.85;center=[0,0,.9]
  else:
   objects,root=scope['build_item'](entry);scope['frame_camera'](objects,1.22)
   render_scale=bpy.context.scene.camera.data.ortho_scale
   lo,hi=bounds(objects);center=[(a+b)/2 for a,b in zip(lo,hi)]
   # Match frame_camera's average bounding-box center, including asymmetric props.
   points=[o.matrix_world@Vector(c) for o in objects if o.type in ('MESH','CURVE') for c in o.bound_box]
   center=list(sum(points,Vector())/len(points))
   objects=[root,*objects]
  lo,hi=bounds(objects)
  # Item animations are local. Doors remain closed and fixed until explicitly used.
  wind=id in ('plantSmall','plantA','plantB','plantE','plantPotted','plantSunflower','plantTallGreen','plantTallPink','plantTallBlue','plantTallPurple')
  animated=kind!='room' and (entry.get('animated',False) or wind) and 'door' not in id.lower()
  rotations={o:o.rotation_euler.copy() for o in objects}
  if animated:
   scene=bpy.context.scene;scene.render.fps=24;scene.frame_start=1;scene.frame_end=49
   for frame in range(49):
    scope['animate_furniture'](objects,frame/48)
    if wind:
     for o in objects:
      if 'leaf' in o.name.lower() or 'flower' in o.name.lower():o.rotation_euler.y=rotations[o].y+.07*math.sin(frame/48*math.tau+o.location.x*2)
    for o in objects:
     for prop in ('location','rotation_euler','scale'):o.keyframe_insert(data_path=prop,frame=frame+1)
   for o in objects:
    if o.animation_data and o.animation_data.action:
     action=o.animation_data.action;action.name=id+' motion';track=o.animation_data.nla_tracks.new();track.name='Motion';track.strips.new('Motion',1,action);o.animation_data.action=None
  export(OUT/(id+'.glb'),objects,animated)
  def yup(v):return [v[0],v[2],-v[1]]
  metadata[id]={'kind':kind,'renderScale':render_scale,'center':yup(center),'min':[lo[0],lo[2],-hi[1]],'max':[hi[0],hi[2],-lo[1]],'animated':animated,'wind':wind}
  if id in ('sofaA','sofaB'):
   # Keep the open space above the seat. One enclosing box fills that space.
   metadata[id]['collisionBoxes']=[]
   for obj in objects:
    if obj.type not in ('MESH','CURVE'):continue
    low,high=bounds([obj])
    metadata[id]['collisionBoxes'].append({'min':[low[0],low[2],-high[1]],'max':[high[0],high[2],-low[1]]})
  print('NATIVE_ITEM',id,flush=True)
 airflow()
 (OUT/'catalog.json').write_text(json.dumps(metadata,indent=2)+'\n')
 sources='// Generated by scripts/3d/export-native.py; IDs match existing saves.\nexport const NATIVE_MODEL_SOURCES: Record<string, number> = {\n'+''.join(f'  "{id}": require("@/assets/3d/native/{id}.glb"),\n' for id in metadata)+'};\n'
 (ROOT/'constants/native-model-sources.ts').write_text(sources)
def airflow():
 clear();scene=scope['setup'](256)
 material=scope['material']('Soft mint airflow','A9D5DF')
 material.diffuse_color=(*material.diffuse_color[:3],.35)
 material.node_tree.nodes.get('Principled BSDF').inputs['Alpha'].default_value=.35
 material.surface_render_method='DITHERED'
 objects=[]
 for x in (-.35,0,.35):objects.append(scope['curve']('Airflow stroke',[(x,-.15,-.1),(x,-.4,-.18),(x,-.65,-.3)],.015,material))
 scene.render.fps=24;scene.frame_start=1;scene.frame_end=49
 for frame in range(49):
  for i,o in enumerate(objects):
   o.location.z=-.04*math.sin(frame/48*math.tau+i*.7)
   o.scale=(1,1,.85+.15*math.sin(frame/48*math.tau+i*.7))
   for prop in ('location','scale'):o.keyframe_insert(data_path=prop,frame=frame+1)
 for o in objects:
  action=o.animation_data.action;track=o.animation_data.nla_tracks.new();track.name='Airflow';track.strips.new('Airflow',1,action);o.animation_data.action=None
 export(OUT/'airflow.glb',objects,True)
def cats():
 from game_cat import export_cats
 export_cats(scope,ARGS,export)
if '--cats' not in ARGS:items()
if '--items' not in ARGS:
 cats()
 # Keep OS launch and React fallback artwork in sync with a cat rebuild.
 import runpy, subprocess
 runpy.run_path(str(ROOT/'scripts/3d/render-native-branding.py'))
 subprocess.run(['node',str(ROOT/'scripts/generate-branding.mjs')],cwd=ROOT,check=True)
