/** Pack small HD texture pages and inexpensive store portraits from Blender frames. */
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const root=process.cwd(),out=path.join(root,'assets/3d');
const entries=JSON.parse(await fs.readFile('scripts/3d/inventory.json','utf8')).entries;
const clips=JSON.parse(await fs.readFile('scripts/3d/clips.json','utf8'));
const clipFlag=process.argv.indexOf('--clips');
const selected=clipFlag<0?null:new Set((process.argv[clipFlag+1]??'').split(','));
if(selected&&[...selected].some(id=>!(id in clips)))throw new Error('Unknown clip in --clips');
const frameSize=768,pageColumns=2,framesPerPage=4;
await fs.mkdir(path.join(out,'atlases'),{recursive:true});
await fs.mkdir(path.join(out,'cat-pages'),{recursive:true});
async function pack(id,count,cellSize=192,columns=8){
 const frames=Array.from({length:count},(_,i)=>path.join(out,'frames',id,`${String(i).padStart(3,'0')}.png`));
 const available=await Promise.all(frames.map(file=>fs.access(file).then(()=>true,()=>false)));
 if(!available.every(Boolean)){
  if(await fs.access(path.join(out,'atlases',id+'.png')).then(()=>true,()=>false))return;
  throw new Error(`Missing render frames for ${id}. Run npm run assets:3d to regenerate the full collection.`);
 }
 const cells=await Promise.all(frames.map(async(file,i)=>({input:await sharp(file).resize(cellSize,cellSize).png().toBuffer(),left:i%columns*cellSize,top:Math.floor(i/columns)*cellSize})));
 await sharp({create:{width:columns*cellSize,height:Math.ceil(count/columns)*cellSize,channels:4,background:'#00000000'}}).composite(cells).png({compressionLevel:9}).toFile(path.join(out,'atlases',id+'.png'));
}
async function packPages(id,count){
 // Walking keeps its complete cycle in the current/next pair. Fetching a new
 // four-frame texture every 111 ms can freeze the feet while the cat moves.
 const walking=id.includes('-walk')||id.includes('-jump');
 const cellSize=walking?384:frameSize, columns=walking?4:pageColumns, cellsPerPage=walking?12:framesPerPage;
 const pageCount=Math.ceil(count/cellsPerPage);
 const frames=Array.from({length:count},(_,i)=>path.join(out,'frames',id,`${String(i).padStart(3,'0')}.png`));
 const available=await Promise.all(frames.map(file=>fs.access(file).then(()=>true,()=>false)));
 if(!available.every(Boolean)){
  const pages=Array.from({length:pageCount},(_,i)=>path.join(out,'cat-pages',`${id}-${String(i).padStart(2,'0')}.webp`));
  if((await Promise.all(pages.map(file=>fs.access(file).then(()=>true,()=>false)))).every(Boolean))return pageCount;
  throw new Error(`Missing HD frames/pages for ${id}. Run npm run assets:3d -- --only cat --refresh.`);
 }

 for(let page=0;page<pageCount;page++){
  const name=`${id}-${String(page).padStart(2,'0')}.webp`;
  const cells=[];
  for(let cell=0;cell<cellsPerPage&&page*cellsPerPage+cell<count;cell++){
   const frame=path.join(out,'frames',id,`${String(page*cellsPerPage+cell).padStart(3,'0')}.png`);
   const metadata=await sharp(frame).metadata();
   if(metadata.width!==frameSize||metadata.height!==frameSize)throw new Error(`Rerender HD frame ${frame}`);
   cells.push({input:walking?await sharp(frame).resize(cellSize,cellSize).png().toBuffer():frame,left:cell%columns*cellSize,top:Math.floor(cell/columns)*cellSize});
  }
  await sharp({create:{width:cellSize*columns,height:cellSize*Math.ceil(cellsPerPage/columns),channels:4,background:'#00000000'}}).composite(cells).webp({quality:90,alphaQuality:100,effort:5}).toFile(path.join(out,'cat-pages',name));
 }
 return pageCount;
}
let catalog='/** Blender clip timings. Generated by scripts/3d/pack.mjs. */\nexport const CAT_SPRITE_CATALOG = {\n';
for(const [id,[count,fps]] of Object.entries(clips))catalog+=`  ${id}: { frameCount: ${count}, fps: ${fps} },\n`;
catalog+='} as const;\nexport type CatSpriteAnimationId = keyof typeof CAT_SPRITE_CATALOG;\nexport type CatSpriteCatalogEntry = (typeof CAT_SPRITE_CATALOG)[CatSpriteAnimationId];\n';
await fs.writeFile('constants/cat-sprite-catalog.ts',catalog);
let sources='/** Small store-preview textures. Gameplay uses CAT_3D_ANIMATION_PAGES. */\nexport const CAT_3D_ANIMATION_SOURCES = {\n';
let pages='/** Only current/next pages are decoded. Room movement fits in that pair. */\nexport const CAT_SPRITE_PAGE_LAYOUT = { frameSize: 768, columns: 2, framesPerPage: 4 } as const;\nexport const CAT_ROOM_MOTION_PAGE_LAYOUT = { frameSize: 384, columns: 4, framesPerPage: 12 } as const;\nexport const CAT_3D_ANIMATION_PAGES = {\n';
for(const skin of ['orange','grey','white']){
 sources+=`  ${skin}: {\n`;pages+=`  ${skin}: {\n`;
 for(const [id,[count]] of Object.entries(clips)){
  const name='cat-'+skin+'-'+id;
  // The splash has a small full idle sheet; other portraits need only four cells.
  if(!selected||selected.has(id))await pack(name,id === "idle" ? count : 4,192,id === "idle" ? 8 : 2);
  sources+=`    ${id}: require("@/assets/3d/atlases/${name}.png"),\n`;
  const pageCount=!selected||selected.has(id)?await packPages(name,count):Math.ceil(count/(id.startsWith('walk')||id.startsWith('jump')?12:framesPerPage));
  pages+=`    ${id}: [${Array.from({length:pageCount},(_,i)=>`require("@/assets/3d/cat-pages/${name}-${String(i).padStart(2,'0')}.webp")`).join(', ')}],\n`;
 }
 sources+='  },\n';pages+='  },\n';
}
sources+='} as const;\n';pages+='} as const;\n';
// Use the actual decoded first splash cell, including its framing and sampling.
if(!selected||selected.has('idle'))await sharp(path.join(out,'atlases/cat-orange-idle.png'))
 .extract({left:0,top:0,width:192,height:192}).png().toFile(path.join(out,'cat-splash.png'));
await fs.writeFile('constants/cat-3d-animation-sources.ts',sources);
await fs.writeFile('constants/cat-3d-animation-pages.ts',pages);
if(!selected)for(const e of entries)if(e.animated||['toy-orangeBall','toy-blueBall','toy-pinkBall','toy-mouse'].includes(e.id))await pack(e.id,8);
console.log(selected?`Packed ${selected.size*3} selected HD cat clips and portraits.`:`Packed ${Object.keys(clips).length*3} HD cat clips with 9 MiB texture pages, small portraits and 28 animated objects.`);
