/** Pack Blender frames into separate textures so only the active cat clip is decoded. */
import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const root=process.cwd(),out=path.join(root,'assets/3d');
const entries=JSON.parse(await fs.readFile('scripts/3d/inventory.json','utf8')).entries;
const clips=JSON.parse(await fs.readFile('scripts/3d/clips.json','utf8'));
await fs.mkdir(path.join(out,'atlases'),{recursive:true});
async function pack(id,count,columns=8){
 const frames=Array.from({length:count},(_,i)=>path.join(out,'frames',id,`${String(i).padStart(3,'0')}.png`));
 const available=await Promise.all(frames.map(file=>fs.access(file).then(()=>true,()=>false)));
 if(!available.every(Boolean)){
  if(await fs.access(path.join(out,'atlases',id+'.png')).then(()=>true,()=>false))return;
  throw new Error(`Missing render frames for ${id}. Run npm run assets:3d to regenerate the full collection.`);
 }

 const cells=await Promise.all(Array.from({length:count},async(_,i)=>({input:await fs.readFile(path.join(out,'frames',id,`${String(i).padStart(3,'0')}.png`)),left:i%columns*192,top:Math.floor(i/columns)*192})));
 await sharp({create:{width:columns*192,height:Math.ceil(count/columns)*192,channels:4,background:'#00000000'}}).composite(cells).png({compressionLevel:9}).toFile(path.join(out,'atlases',id+'.png'));
}
let catalog='/** Original Blender animation clips. Generated by scripts/3d/pack.mjs. */\nexport const CAT_SPRITE_CATALOG = {\n';
for(const [id,[count,fps]] of Object.entries(clips))catalog+=`  ${id}: { frameCount: ${count}, fps: ${fps} },\n`;
catalog+='} as const;\nexport type CatSpriteAnimationId = keyof typeof CAT_SPRITE_CATALOG;\nexport type CatSpriteCatalogEntry = (typeof CAT_SPRITE_CATALOG)[CatSpriteAnimationId];\n';
await fs.writeFile('constants/cat-sprite-catalog.ts',catalog);
let sources='/** Per-coat, per-animation textures generated from the editable Blender clips. */\nexport const CAT_3D_ANIMATION_SOURCES = {\n';
for(const skin of ['orange','grey','white']){
 sources+=`  ${skin}: {\n`;
 for(const [id,[count]] of Object.entries(clips)){await pack('cat-'+skin+'-'+id,count);sources+=`    ${id}: require("@/assets/3d/atlases/cat-${skin}-${id}.png"),\n`;}
 sources+='  },\n';
}
sources+='} as const;\n';await fs.writeFile('constants/cat-3d-animation-sources.ts',sources);
for(const e of entries)if(e.animated||['toy-orangeBall','toy-blueBall','toy-pinkBall','toy-mouse'].includes(e.id))await pack(e.id,8);
await fs.writeFile('scripts/3d/clips.json',JSON.stringify(clips,null,2)+'\n');
console.log('Packed',Object.keys(clips).length*3,'cat clips and 28 animated objects.');
